# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://allisonmachado.github.io/
# baseurl: /sustain/
title: Allison Machado
author: Allison Machado
description: Currículo e blog pessoal
avatar: profile.jpg
email: aallison93@gmail.com
github: allisonmachado
linkedin: allisonmachado